# Generated by Django 2.2.7 on 2019-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enterance_year',
            field=models.IntegerField(default=1395),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('ce', 'computer engineering'), ('cs', 'conputer science'), ('ee', 'electrical engineering')], default='1', max_length=2),
        ),
    ]
