# Generated by Django 2.2.7 on 2019-11-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enterance_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='major',
        ),
    ]
