# Generated by Django 2.2.7 on 2019-11-07 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='broker.ApplicationResponse'),
        ),
        migrations.AlterField(
            model_name='textanswer',
            name='value',
            field=models.CharField(default='kooooon', max_length=100, verbose_name='text_value'),
        ),
    ]
