# Generated by Django 2.2.7 on 2019-11-08 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='broker.Question'),
        ),
        migrations.AlterField(
            model_name='applicationform',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='authentication.Instructor'),
        ),
        migrations.AlterField(
            model_name='applicationresponse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='authentication.Student'),
        ),
        migrations.AlterField(
            model_name='question',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='broker.ApplicationForm'),
        ),
    ]
