# Generated by Django 2.2.7 on 2019-11-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_auto_20191108_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationresponse',
            name='state',
            field=models.CharField(choices=[('p', 'pending'), ('a', 'approved'), ('r', 'rejected')], default='p', max_length=1),
            preserve_default=False,
        ),
    ]
