# Generated by Django 2.2.7 on 2019-11-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_applicationresponse_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TextAnswer',
            new_name='TextualAnswer',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default=None, max_length=255, verbose_name='type'),
            preserve_default=False,
        ),
    ]
