# Generated by Django 2.2.7 on 2019-11-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_auto_20191110_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='type',
            field=models.CharField(default='None', max_length=255, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textualanswer',
            name='value',
            field=models.CharField(default='', max_length=100, verbose_name='text_value'),
        ),
    ]
